### ISSUE TITLE
Can't access the second Local Drive (0.4.6.0)

### ISSUE THREAD

**Issue by p0nkr4t** [duke7553/files-uwp#24]
Installed succesfully 0.4.6.0 release and rebooted my laptop.
But in the menu I can only see my system disk, OneDrive and removable device (which is not installed in). The second Local disk is missed.
How to fix this?
Thanks in advance!

**Comment by duke7553** [comment]
Hey there. I have a new solution coming very soon that addresses this problem. You'll be able to view everything that has a drive letter: partition, removable drive, or other local disks. 
![snipofdrives](https://user-images.githubusercontent.com/20365014/52749415-1b985700-2fb7-11e9-9563-309ac3ff5665.jpg)
Here's a snip of my PC which currently has a two local disks, the usual DVD, and one USB drive plugged in. Files will be able to recognize all of these. However, phone visibility requires extra support which I'm disabling for now.

**Comment by markrjr** [comment]
Maybe outside the context of this issue, but I'm just curious as to how you solved this? I know that there are a limited amount of traditional Win32 APIs available for access to UWP apps. Did you use something like [GetLogicalDrives](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getlogicaldrives)?

**Comment by duke7553** [comment]
Absolutely! No legacy Windows APIs are used. This may be seen as an incedibly crummy solution, but I now do the following on startup: 

1. Gather a list of Removable Drives (USB flash drives and DVD drive) from [KnownFolders.RemovableDevices](https://docs.microsoft.com/en-us/uwp/api/windows.storage.knownfolders.removabledevices#Windows_Storage_KnownFolders_RemovableDevices)
2. Loop through ALL possible drive letters (excluding C:\), checking if they can be accessed.
3. Those that do not throw an exception are added to a collection.
4. Everything in this collection is added as a NavigationViewItem, but if its drive letter corresponds to one in the list from step one, it is displayed to the user as "Removable". (Otherwise, it's another Local Disk)
*This now excludes MTP devices because it requires some extra work to handle.
![drivedisplay](https://user-images.githubusercontent.com/20365014/52829274-18c26280-309a-11e9-82c9-b9a415591062.jpg)

**Comment by duke7553** [comment]
Now available in v0.4.7
