### ISSUE TITLE
Advance the design of tabs in background

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#280]
**Is your feature request related to a problem? Please describe.**
Maybe the design of tabs in the background is a little bit too minimalistic?

**Describe the solution you'd like**
Maybe add dividers for those apps?

**Describe alternatives you've considered**
currently no other idea.

**Additional context**
This is the current design:
![image](https://user-images.githubusercontent.com/42591237/68499865-a06c8480-025a-11ea-88c0-4ec71404a3d4.png)

This is Microsoft Edge:
![image](https://user-images.githubusercontent.com/42591237/68499891-b11cfa80-025a-11ea-9ffd-cf7b8c501453.png)

Maybe these seperators would be feasible?
![image](https://user-images.githubusercontent.com/42591237/68499965-d3167d00-025a-11ea-8c04-5ff316e869ed.png)

Probably in combination with: 
https://github.com/duke7553/files-uwp/issues/279#issuecomment-551929631

**Comment by yaichenbaum** [comment]
The current version in master actually looks like this:
![image](https://user-images.githubusercontent.com/39923744/68504235-84ed8380-0232-11ea-824a-f3df1937de39.png)

There is also an open issue to improve the colors #120.
Since this issue has already been addressed and will roll out in the next update (still trying to get the package to build) I will close this issue.
