### ISSUE TITLE
3rd party plugins 

### ISSUE THREAD

**Issue by moutasem1989** [duke7553/files-uwp#343]
allow third parties to develop and add plugins through Microsoft store such as file formats support, files quick view, compression formats handling, adding actions to command panel, custom icons,

**Comment by yaichenbaum** [comment]
We have been getting a lot of requests for this. Are you interested in creating a plugin?

**Comment by yaichenbaum** [comment]
Just commenting that QuickLook integration will be available when v0.7 rolls out.

**Comment by SOI7** [comment]
Another third party app that could receive support from Files UWP is Windows Terminal

**Comment by yaichenbaum** [comment]
@SOI7 How would you recommend adding support for Windows Terminal?

**Comment by SOI7** [comment]
> @SOI7 How would you recommend adding support for Windows Terminal?

As it is now, Files UWP can open a cmd terminal starting from the directory where you right click and launch the command. However, I'm currently using Windows Terminal as a replacement for cmd and it would be cool if we could set it as the default console app in Files, so that when you right click in an empty spot and select "Open in Terminal" it launches Windows Terminal instead of the builtin cmd

**Comment by szaimen** [comment]
> so that when you right click in an empty spot and select "Open in Terminal" it launches Windows Terminal instead of the builtin cmd

Yes, that would be really nice! 
And I guess, it should get opened with windows terminal automatically, if it is installed?

**Comment by SOI7** [comment]
> > so that when you right click in an empty spot and select "Open in Terminal" it launches Windows Terminal instead of the builtin cmd
> 
> Yes, that would be really nice!
> And I guess, it should get opened with windows terminal automatically, if the app is installed?

Maybe. Some people may prefer good old cmd even if they have Terminal installed, so a toggle could be safer. PowerShell is another big factor in the game, however there's a chance that Terminal could open the current path in PowerShell instead of cmd if you set it as the default profile, but sadly I can't verify this since, alas, in win32 Explorer you can't open any folder in Terminal. But that is another thing and I don't want to go off topic

**Comment by yaichenbaum** [comment]
So what we would probably want is a toggle in settings to choose cmd, powershell or terminal. In the case that terminal is chosen then I imagine terminal would open with the default profile.

**Comment by SOI7** [comment]
> So what we would probably want is a toggle in settings to choose cmd, powershell or terminal. In the case that terminal is chosen then I imagine terminal would open with the default profile.

Exactly

**Comment by yaichenbaum** [comment]
Full support for Windows Terminal has been added to Files UWP with v0.7.5. We will continue work on integrations with Windows 10 features as well as integrations with 3rd part apps. If there is a specific integration that you would like to see added, make sure to open an issue or pull request.
