### ISSUE TITLE
Open executable file with administrative rights

### ISSUE THREAD

**Issue by KaKi87** [duke7553/files-uwp#350]
Like mentioned in #128 and #244, executable files can't be opened with administrative rights, but this should definitely be a feature. Thanks

**Comment by yaichenbaum** [comment]
@duke7553 I believe this is going to be fixed with 0.7, can you confirm?

**Comment by lukeblevins** [comment]
@yair100 Indeed! This behavior is corrected with v0.7. Please reopen if you can reproduce after the next release.

**Comment by KaKi87** [comment]
Still waiting for that v0.7 ^^

**Comment by yaichenbaum** [comment]
@KaKi87 v0.7 includes many changes and some of them are not ready, perhaps we should keep issues open until the changes are actually sent out.

**Comment by KaKi87** [comment]
@duke7553 @yair100 Any ETA on v0.7 ? Since some issues have been closed, I'm assuming that I should be able to download it somewhere. Thanks

**Comment by yaichenbaum** [comment]
@KaKi87 Sorry about that, we are waiting for a bug in Visual Studio that is preventing us from creating packages to be fixed. Someone on the Visual Studio team confirmed that the issue is fixed on their end but gave no estimated time when it will be sent out.
In the meantime we are working on performance improvements and I am really excited to share that there are some pretty major improvements coming soon that will load large directories a lot faster.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
