### ISSUE TITLE
[Opinion][Feature request] Keyboard navigation

### ISSUE THREAD

**Issue by wilmhit** [duke7553/files-uwp#367]
Hi,
I've used this app a little bit and I must say I am impressed. App is very snappy, UI has is not cluttered and it is almost ready to replace windows explorer daily. Few features it lacks:

1. **Most important: keyboard navigation**. (alt+d, tab to autocomplete while in address bar, arrow down after opened a folder to select files). So far you've done very good job regarding shortcuts. I love how it is all shown in tooltips/context menus. But app like file explorer needs to be ready for keyboard only navigation.

2. Customizable left panel. I have uninstalled onedrive a while ago and replaced it with MEGA. I dont even have onedrive folder on my drive and it still shows in your explorer. Quickest fix would be to add option to change its location in settings (custom locations tab). Or on/off switch for onedrive. Also a lot of users like windows' quick access.

3. Custom icons. App doesn't respect custom icons set for folders. If you go to user folder, folders like downloads, pictures etc. need its icons.

4. **Hidden and protected files**. It should be shown in properties window. Also while trying to change name of protected file it shows error: This file already exists or something like that.

5. UI tweaks. UI doesn't need much more love. It is as almost as good as possible. Few of my thoughts:
   - scroll bar in folders isn't aligned to the left. Instead it floats on the right side of folder contents.
   - Maybe you should add some semi-transparent elements. It's just suggestion. You must consider
     impact on performance.
   - Most recent windows builds have different layout for downloads folder. It is very readable. If you
     will make something like this, app will feel very polished.

So far i've been using this app only a little bit because it is still way quicker to use default explorer, but this project has a lot of potential. I just love how loading works. app is responsive all the time. That basically fixes problems with loading big folders. I wouldn't be surprised if microsoft will try to contact you after few months (especially seeing their take on on uwp explorer).

**Comment by yaichenbaum** [comment]
Thank you for creating this issue, everything is well said and we plan on addressing all your feedback. In order to keep the tracking of issues simple can I ask you to comment on some of the existing issues already created?
1. We are tracking keyboard navigation related issues in #9 
2. There are plans to support more file storage services in the future, please see #242.
3. I am not sure if we can detect the custom icons but it would make tracking easier if you created a separate issue so we can update you if and when we do find a way to do that.
4. We are trying to find a way to access these files and are tracking it here #26 
5. In the next update there will be an option to show "acrylic" in the left sidebar, in addition we are planning an improved downloads page much like the ones made in recent versions of Windows, we are tracking this here #131.

The last point about loading large folders is a big pain point and we are trying to come up with workarounds.

Please comment if you still have any issues or things that I did not point you in the right direction to.

**Comment by yaichenbaum** [comment]
@duke7553 has spent some time working on the speed of loading large directories and has managed to decrease the loading time by over 75%!
I am going to close this issue and if there is anything that I missed feel free to reopen this issue or to create a new one.
