### ISSUE TITLE
Unexpected "previous" gesture

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#473]
EDIT: There is a gesture to go to the previous directory, and sometimes you do it accidentally and it could be annoying

**Files v0.7.2**

**Comment by yaichenbaum** [comment]
This is because of a swipe gesture that lets you use a touch screen to go back to the previous directory. We will need to look into a replacement that is more accurate and won't cause the unexpected behavior you noticed.

**Comment by xPoppyx** [comment]
So, it is not a bug I suppose, besides that the scroll bar is not related to this at all, just an unexpected "gesture"

**Comment by yaichenbaum** [comment]
@xPoppyx Correct, we want to include gestures in the app but we need to make sure they don't have any side effects.

**Comment by MaxVonMustermann** [comment]
I personally like the idea of gestures, but I also met some inconviniences like it being triggered too easily with a mouse. For future releases, I would appreciate, if those gestures could optionally be turned off/customized. Regarding customization, it would be cool if the user could navigate between tabs when swiping, rather than going back and forth. This would especially be useful when using a mouse that features back and forth button on the side. 
I use the extension crxMouse Chrome™ Gestures on my browser, which really improves the user experience in the regards mentioned in this post, looking into that might help (this is no advertisement, don't get me wrong). Thanks for the work on Files UWP and all the best to the team!

**Comment by yaichenbaum** [comment]
Due to the inconsistent behavior of this gesture, it will be removed when the v0.7.3 release is rolled out. We will explore adding new gestures in the future, but only when we are confident that it won't cause any unexpected side effects.
