### ISSUE TITLE
Some bugs/questions/Feature request [v0.7.7]

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#638]
**1.**  **Feature request:** Display this date format -> 04/19/2020 20:30, instead of "3 days ago" for the most recent files
  - in case you are not interested in changing this, the text "5 days ago", "4 hours ago", etc. are they translated automatically? because they are still in English

**2.** ------------------------------

**3.** -----------------------------

**4.** ------------------------------

**5.** -----------------------------

**6.** The shortcuts do not appear (this happens from previous versions)

**8.** this dialog is white when the app was in dark mode
![Anotación 2020-04-22 124431](https://user-images.githubusercontent.com/61259627/80010195-10349b80-8498-11ea-9d97-4a81cdf22847.png)

**Comment by yaichenbaum** [comment]
1. You can change the date format in the apps settings.
6. Shortcuts are not supported yet #328.
8. Can you mention the missing strings in #37? The second dialog is going to be replaced with a modern one instead of the Windows 8 style, the theme issue should be fixed when that is taken care of.

_It would help if you opened individual issues for the other items, this way if someone wants to work on one of the items, they can do that without taking up all the other issues._

**Comment by tsvietOK** [comment]
@yaichenbaum As i understand, currently it is not possible to translate this string, as new tab detection based on "new tab" string.

**Comment by yaichenbaum** [comment]
@tsvietOK Which string?

**Comment by xPoppyx** [comment]
changing the date format only affects older files:
![Anotación 2020-04-22 144546](https://user-images.githubusercontent.com/61259627/80021138-1468b500-84a8-11ea-9470-b9b6500cc316.png)
![Anotación 2020-04-22 144624](https://user-images.githubusercontent.com/61259627/80021143-16327880-84a8-11ea-9d5d-6651cab4ef95.png)
also that "11 hours ago" is not automatically translated into Spanish

**Comment by tsvietOK** [comment]
@yaichenbaum "New tab" string. As in your PR #640 . I think this change could break new tab detection.

**Comment by xPoppyx** [comment]
https://github.com/duke7553/files-uwp/issues/638#issuecomment-617963511
