### ISSUE TITLE
Permission dialog

### ISSUE THREAD

**Issue by ATecSolution** [duke7553/files-uwp#65]
This is not so much an issue but more of a question for my own uwp development, so please close it if you want to.
How does the app know not to show the file permission dialog once the user already gave permission?

**Comment by duke7553** [comment]
I can't allow this conversation to continue on the issues page, but since you've made some great contributions, I'll tell you. 
In Files' case, you have to use a try/catch block to handle the AccessDeniedException (I think...) that gets thrown if permission is not available for the approperiate methods to run. In other words try to run code, and when the exception is caught, display a ContentDIalog.

**Comment by ATecSolution** [comment]
Ok, thank you so much!
