### ISSUE TITLE
Multiple File Seleection

### ISSUE THREAD

**Issue by Mahan3340** [duke7553/files-uwp#724]
**Is your feature request related to a problem? Please describe.**
Select All is not always the needed case. most of the times I just want to select a few files and folders and perform some action on them

**Describe the solution you'd like**
Aside from the select all option, add an option to make the current files and folders selectable (using a checkbox or sth like that) then, while we are in the selection mode, we can select a few files or folders by single taps and delete/cut/copy or select them all.

**Comment by yaichenbaum** [comment]
@Mahan3340 Thank you for opening this issue with your feedback, I just wanted to let you know that we are tracking this same issue here #290. I am going to close this issue as it's already being tracked, but make sure to subscribe or comment on #290 so that you will get informed when it's addressed.
