### ISSUE TITLE
downloads keeps crashing

### ISSUE THREAD

**Issue by Hamzaparekh** [duke7553/files-uwp#76]
the downloads page always crashes the app

**Comment by duke7553** [comment]
What app version?

**Comment by duke7553** [comment]
Please reopen when you can provide the app version and Windows version. Thanks!

**Comment by garylavayou** [comment]
I also suffer from this problem with version 0.4.9.

I have changed the default place (`C:\Users\xxx\Downloads`) of my download folder to another place. The old folder leaves empty. In this case, the download folder can be opened inside Files.

However, after I delete the empty folder, and try to open the download folder, the App crashes. 
If I add the empty folder back, the problem is gone.
